version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    post_build:
      - mv docs/build/html/* $READTHEDOCS_OUTPUT/html
sphinx:
  configuration: docs/source/conf.py  
# Optional outputs
formats:
   - pdf
#    - epub
python:
   install:
   - requirements: docs/requirements.txt