name: Publish Repgen Release to PyPI

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read  # Grants access to read the repository contents
      id-token: write # Grants access to generate an OpenID Connect (OIDC) token

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install build dependencies
      run: python -m pip install --upgrade pip setuptools wheel

    - name: Build the package
      run: python setup.py sdist bdist_wheel

    - name: Publish to PyPI via trusted publisher
      run: |
        python -m pip install twine
        twine upload --repository pypi dist/*

    - name: Clean up build artifacts
      run: rm -rf dist build *.egg-info
